// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq-LKNzIQcboUiRWYzAndjBSINotHHgcA',
    appId: '1:802498209800:web:54db1b645d5ca8412309bd',
    messagingSenderId: '802498209800',
    projectId: 'project-uiux',
    authDomain: 'project-uiux.firebaseapp.com',
    storageBucket: 'project-uiux.appspot.com',
    measurementId: 'G-YMG280NFV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZc9JeLgybqTkib6180XcOmNyHxkmZ5ts',
    appId: '1:802498209800:android:f10bb75a0e8526d82309bd',
    messagingSenderId: '802498209800',
    projectId: 'project-uiux',
    storageBucket: 'project-uiux.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcVIJJf1iq8a0jMmGEeaKGvsb6UVobr4c',
    appId: '1:802498209800:ios:74816b680cabe8722309bd',
    messagingSenderId: '802498209800',
    projectId: 'project-uiux',
    storageBucket: 'project-uiux.appspot.com',
    iosClientId: '802498209800-j9neq9lfs45agskd1j51rkgp8pg771eb.apps.googleusercontent.com',
    iosBundleId: 'com.example.komipaWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcVIJJf1iq8a0jMmGEeaKGvsb6UVobr4c',
    appId: '1:802498209800:ios:74816b680cabe8722309bd',
    messagingSenderId: '802498209800',
    projectId: 'project-uiux',
    storageBucket: 'project-uiux.appspot.com',
    iosClientId: '802498209800-j9neq9lfs45agskd1j51rkgp8pg771eb.apps.googleusercontent.com',
    iosBundleId: 'com.example.komipaWeb',
  );
}
